# Generated by Django 6.0.7 on 2026-07-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Grupo de Producto',
                'verbose_name_plural': 'Grupos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Etiqueta')),
                ('color', models.CharField(choices=[('primary', '🔵 Azul'), ('success', '🟢 Verde'), ('danger', '🔴 Rojo'), ('warning', '🟡 Amarillo'), ('info', '🔷 Celeste'), ('dark', '⚫ Negro'), ('purple', '🟣 Morado'), ('orange', '🟠 Naranja')], default='primary', max_length=20, verbose_name='Color')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_auto', models.BooleanField(default=False, verbose_name='¿Es automática?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_level1', models.CharField(blank=True, max_length=4, verbose_name='Nivel 1')),
                ('code_level2', models.CharField(blank=True, max_length=4, verbose_name='Nivel 2')),
                ('code_level3', models.CharField(blank=True, max_length=4, verbose_name='Nivel 3')),
                ('code_level4', models.CharField(blank=True, max_length=4, verbose_name='Nivel 4')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('factory_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Fábrica')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(default='Unidad', max_length=20, verbose_name='Unidad')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Venta')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Actual')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Mínimo')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productgroup')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
