# Generated by Django 6.0.7 on 2026-07-23 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Venta')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('customer_nit', models.CharField(blank=True, max_length=20, verbose_name='NIT/CI')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('CREDITO', 'Crédito'), ('QR', 'QR / Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vuelto')),
                ('is_quotation', models.BooleanField(default=False, verbose_name='¿Es Cotización/Proforma?')),
                ('invoice_type', models.CharField(choices=[('SIN_IVA', 'Sin IVA (Consumidor Final)'), ('CON_IVA', 'Con Factura (16%)')], default='SIN_IVA', max_length=20, verbose_name='Tipo de Facturación')),
                ('invoice_number', models.CharField(blank=True, max_length=20, verbose_name='Nº Factura')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('COTIZACION', 'Cotización/Proforma')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
