# Generated by Django 6.0.7 on 2026-07-24 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Respaldo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('RESTAURADO', 'Restaurado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restaurado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
    ]
