# Generated by Django 6.0.7 on 2026-07-23 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='M&S Melamina', max_length=200, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(default='123456789', max_length=20, verbose_name='NIT')),
                ('address', models.TextField(blank=True, default='Santa Cruz - Bolivia', verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, default='+(591) 3-1234567', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='info@msmelamina.com', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('currency', models.CharField(default='Bs.', max_length=10, verbose_name='Moneda')),
                ('currency_symbol', models.CharField(default='Bs.', max_length=5, verbose_name='Símbolo de Moneda')),
                ('iva_rate', models.IntegerField(choices=[(0, '0% (Exento)'), (13, '13% (Bolivia)'), (16, '16% (Con Factura)')], default=13, verbose_name='Tasa de IVA (%)')),
                ('receipt_footer', models.TextField(blank=True, default='¡Gracias por su compra!', verbose_name='Pie de página del recibo')),
                ('receipt_message', models.TextField(blank=True, default='Este documento es un comprobante de venta', verbose_name='Mensaje en el recibo')),
                ('print_auto', models.BooleanField(default=False, verbose_name='Imprimir recibo automáticamente')),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Número de copias')),
                ('low_stock_alert', models.IntegerField(default=10, verbose_name='Alerta de stock bajo (unidades)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuraciones de la Empresa',
            },
        ),
    ]
