# Generated by Django 6.0.7 on 2026-07-23 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Turno Mañana'), ('AFTERNOON', 'Turno Tarde')], max_length=20, verbose_name='Tipo de Turno')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Efectivo Inicial')),
                ('final_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Efectivo Final')),
                ('sales_count', models.IntegerField(default=0, verbose_name='Número de Ventas')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-start_time'],
            },
        ),
    ]
