# Generated by Django 6.0.7 on 2026-07-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('EXPORT', 'Exportar'), ('PRINT', 'Imprimir'), ('CANCEL', 'Anular'), ('RESTORE', 'Restaurar')], max_length=20, verbose_name='Acción')),
                ('module', models.CharField(choices=[('PRODUCTS', 'Productos'), ('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('USERS', 'Usuarios'), ('REPORTS', 'Reportes'), ('BACKUP', 'Respaldos'), ('SETTINGS', 'Configuración'), ('TURNS', 'Turnos'), ('AUDIT', 'Auditoría')], max_length=20, verbose_name='Módulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action', 'module'], name='audit_audit_action_72b113_idx')],
            },
        ),
    ]
